### ISSUE TITLE
Q: what permission are needed to run server on the phone?

### ISSUE THREAD

**Issue by mw66** [Davenchy/general_json_rpc#2]
Q: what permission are needed to run server on the phone?

Thanks.

**Comment by Davenchy** [comment]
To run a server on a phone, the required permissions depend on the application's functionality. For Android devices, one essential permission is `android.permission.INTERNET`. This permission enables the app to access the internet, facilitating tasks like sending and receiving data, communicating with servers, and downloading content. By declaring this permission in the app's manifest file, it gains the necessary access to internet-related functionalities. Without it, the app won't be able to perform network-related tasks effectively.

Flutter usually adds this permission in development process but for the release version you have to add it yourself, check flutter docs for more information.

[https://docs.flutter.dev/deployment/android#reviewing-the-app-manifest](https://docs.flutter.dev/deployment/android#reviewing-the-app-manifest)
